
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param arg0
     * @return
     *     returns proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://ws/", className = "proxy.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://ws/", className = "proxy.GetCompteResponse")
    @Action(input = "http://ws/BanqueService/getCompteRequest", output = "http://ws/BanqueService/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConvertMadtoEuro")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConvertMadtoEuro", targetNamespace = "http://ws/", className = "proxy.ConvertMadtoEuro")
    @ResponseWrapper(localName = "ConvertMadtoEuroResponse", targetNamespace = "http://ws/", className = "proxy.ConvertMadtoEuroResponse")
    @Action(input = "http://ws/BanqueService/ConvertMadtoEuroRequest", output = "http://ws/BanqueService/ConvertMadtoEuroResponse")
    public double convertMadtoEuro(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListComptes", targetNamespace = "http://ws/", className = "proxy.GetListComptes")
    @ResponseWrapper(localName = "getListComptesResponse", targetNamespace = "http://ws/", className = "proxy.GetListComptesResponse")
    @Action(input = "http://ws/BanqueService/getListComptesRequest", output = "http://ws/BanqueService/getListComptesResponse")
    public List<Compte> getListComptes();

}
